# Generated by Django 3.2.8 on 2021-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alternate',
            field=models.ImageField(default='images/img2_SUlRxwK.png', upload_to='images/'),
        ),
    ]
