# Generated by Django 3.2.8 on 2021-11-07 21:24

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20211108_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/', validators=[store.validators.ImageFileMimeValidator()]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alternate',
            field=models.ImageField(default='images/default.png', upload_to='images/', validators=[store.validators.ImageFileMimeValidator]),
        ),
    ]
