# Generated by Django 3.2.8 on 2021-11-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20211108_0237'),
        ('store', '0017_auto_20211108_0254'),
    ]

    operations = [
    ]
