# Generated by Django 3.2.8 on 2021-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userbase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
