# Generated by Django 3.2.8 on 2021-10-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userbase_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='town_city',
        ),
    ]
