# Generated by Django 3.2.8 on 2021-10-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userbase_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={},
        ),
    ]
