# Generated by Django 3.2.8 on 2021-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userbase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
