# Generated by Django 3.2.8 on 2021-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211017_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
