# Generated by Django 3.2.8 on 2021-10-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userbase_two_fa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
