# Generated by Django 3.2.8 on 2021-11-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211102_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Buyer'), (2, 'Unverified_Seller'), (3, 'Verified_Seller')], default=1),
        ),
    ]
