# Generated by Django 3.2.8 on 2021-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userbase_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='userbase',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Buyer only'), (2, 'Buyer + Unverified_Seller'), (3, 'Buyer + Verified_Seller')], default=1),
        ),
    ]
