# Generated by Django 3.2.8 on 2021-11-03 07:42

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20211102_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='verification_document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='verification_documents/', validators=[]),
            preserve_default=False,
        ),
    ]
