# Generated by Django 3.2.8 on 2021-11-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20211105_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyer(s)'},
        ),
        migrations.AlterModelOptions(
            name='customlog',
            options={'verbose_name': 'Login - Logout Log', 'verbose_name_plural': 'Login - Logout Log(s)'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Seller(s)'},
        ),
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User(s)'},
        ),
    ]
