# Generated by Django 3.1.5 on 2021-11-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20211107_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='otp',
            field=models.SmallIntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
