# Generated by Django 3.2.8 on 2021-11-07 21:16

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20211107_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='user_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='verification_document',
            field=models.FileField(upload_to='verification_documents/', validators=[account.validators.DocumentFileMimeValidator()]),
        ),
    ]
