# Generated by Django 3.2.8 on 2021-11-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211108_0237'),
        ('orders', '0009_auto_20211108_0246'),
    ]

    operations = [
    ]
