# Generated by Django 3.2.8 on 2021-10-14 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='verification_document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='verification_documents/'),
            preserve_default=False,
        ),
    ]
