# Generated by Django 3.2.8 on 2021-10-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_seller_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
