# Generated by Django 3.2.8 on 2021-11-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userbase_verification_document'),
        ('seller', '0006_alter_seller_verification_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userbase',),
        ),
    ]
