# Generated by Django 3.2.8 on 2021-11-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20211103_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
